import type { EmployeeInput } from "./types";

export const SEED_EMPLOYEES: EmployeeInput[] = [
  {
    firstName: "Dave",
    lastName: "Gray",
    title: "Engineering lead",
    department: "Engineering",
    email: "dave.gray@northwind.team",
    location: "Austin",
    status: "active",
    startDate: "2019-04-08",
  },
  {
    firstName: "John",
    lastName: "Smith",
    title: "People partner",
    department: "People",
    email: "john.smith@northwind.team",
    location: "London",
    status: "active",
    startDate: "2020-01-13",
  },
  {
    firstName: "Amira",
    lastName: "Hassan",
    title: "Product designer",
    department: "Design",
    email: "amira.hassan@northwind.team",
    location: "Nairobi",
    status: "active",
    startDate: "2021-06-21",
  },
  {
    firstName: "Leo",
    lastName: "Park",
    title: "Backend engineer",
    department: "Engineering",
    email: "leo.park@northwind.team",
    location: "Seoul",
    status: "active",
    startDate: "2022-02-14",
  },
  {
    firstName: "Sofia",
    lastName: "Reyes",
    title: "Sales director",
    department: "Sales",
    email: "sofia.reyes@northwind.team",
    location: "Madrid",
    status: "active",
    startDate: "2018-09-03",
  },
  {
    firstName: "Noah",
    lastName: "Adeyemi",
    title: "Ops manager",
    department: "Operations",
    email: "noah.adeyemi@northwind.team",
    location: "Lagos",
    status: "leave",
    startDate: "2021-11-01",
  },
  {
    firstName: "Elena",
    lastName: "Kovacs",
    title: "Finance lead",
    department: "Finance",
    email: "elena.kovacs@northwind.team",
    location: "Berlin",
    status: "active",
    startDate: "2020-08-17",
  },
  {
    firstName: "Marcus",
    lastName: "Chen",
    title: "Frontend engineer",
    department: "Engineering",
    email: "marcus.chen@northwind.team",
    location: "Toronto",
    status: "active",
    startDate: "2023-03-06",
  },
  {
    firstName: "Priya",
    lastName: "Nair",
    title: "Recruiter",
    department: "People",
    email: "priya.nair@northwind.team",
    location: "Bengaluru",
    status: "active",
    startDate: "2022-10-10",
  },
  {
    firstName: "Jonah",
    lastName: "Hale",
    title: "Support specialist",
    department: "Operations",
    email: "jonah.hale@northwind.team",
    location: "Remote",
    status: "offboarding",
    startDate: "2024-01-22",
  },
  {
    firstName: "Camille",
    lastName: "Dubois",
    title: "Brand designer",
    department: "Design",
    email: "camille.dubois@northwind.team",
    location: "Lisbon",
    status: "leave",
    startDate: "2021-05-19",
  },
  {
    firstName: "Wes",
    lastName: "Okonkwo",
    title: "Security engineer",
    department: "Engineering",
    email: "wes.okonkwo@northwind.team",
    location: "Accra",
    status: "active",
    startDate: "2023-07-31",
  },
];
